## YAML Template.
spring:
    profiles:
        active: dev
    messages:
        basename: i18n/messages
        encoding: UTF-8
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
#maximum number of milliseconds that a client will wait for a connection
        hikari:
            connectionTimeout: 30000
#minimum number of idle connections maintained by HikariCP in a connection pool
            minimumIdle: 1
#maximum pool size

            maximumPoolSize: 2

#maximum idle time for connection
            idleTimeout: 90000
# maximum lifetime in milliseconds of a connection in the pool after it is closed.
            maxLifetime: 1800000
#default auto-commit behavior.
            autoCommit: true
            leakDetectionThreshold: 60000
            connectionTestQuery: SELECT 1
            poolName: HikariPool
server:
    servlet:
        context-path: /jwt-service
security:
    jwt.secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
    jwt.expiration-time: 3600000